url: https://seesawlabs.github.io
baseurl: /

# Site settings
title: SeeSaw Labs
email: info@seesawlabs.com.com
description: "Custom Mobile And Web Application Development, Consulting and Training."
keywords: "Software,Development,Consulting,Mobile,Website,Yii Training"

# Build settings
markdown: kramdown
permalink: pretty

destination: build
source: build
